config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("stock_price_alert.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("alerts/", include("stock_price_alert.alerts.urls", namespace="alerts"))
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

stock_price_alert/alerts/urls.py
from django.urls import path

from .views import view_alerts, add_alerts, remove_alert

app_name = "alerts"
urlpatterns = [
    path("view_alerts/", view=view_alerts, name="view_alerts"),
    path("add_alerts/", view=add_alerts, name="add_alerts"),
    path("remove_alert/", view=remove_alert, name="remove_alert"),

]

stock_price_alert/users/urls.py
from django.urls import path

from stock_price_alert.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

stock_price_alert/alerts/models.py
import uuid
from django.db import models
from django_extensions.db.models import TimeStampedModel
from stock_price_alert.users.models import User


class Alert(TimeStampedModel):
    scrip_symbol = models.CharField(max_length=50)
    exchange_name = models.CharField(max_length=10)
    price = models.FloatField()
    percentage = models.FloatField(blank=True, null=True)
    intraday_alert = models.BooleanField(default=False, help_text='Set if you want to check intraday prices')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

stock_price_alert/users/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, UUIDField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)
    phone_number = PhoneNumberField(blank=True)
    address = CharField(_("Address of User"), blank=True, max_length=255)
    uuid = UUIDField(default=uuid.uuid4, editable=False, unique=True)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

stock_price_alert/alerts/forms.py
import random
from django.contrib.auth import get_user_model
from django.forms import ModelForm, CharField, BooleanField, FloatField, Form
from django.forms.widgets import TextInput
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Button, Field
from crispy_forms.bootstrap import Accordion, AccordionGroup, Tab, TabHolder, FormActions

User = get_user_model()


class AlertFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(AlertFormSetHelper, self).__init__(*args, **kwargs)
        self.form_method = 'post'
        self.render_required_fields = True
        r = random.randint(1, 100)
        self.layout = Layout(
            Accordion(

                Fieldset('Alert Data', 'scrip_symbol', 'exchange_name', 'price', 'percentage',
                         'intraday_alert')

            )
        )


class AlertForm(Form):
    scrip_symbol = CharField(max_length=50,
                             widget=TextInput(attrs={'placeholder': 'Scrip symbol like GOOGL'}))
    exchange_name = CharField(max_length=10,
                              widget=TextInput(attrs={'placeholder': 'Exchange names like NSE or NASDAQ'}))
    price = FloatField(widget=TextInput(attrs={'placeholder': 'Price of the scrip at which you want alert'}))
    percentage = FloatField(required=False,
                            widget=TextInput(attrs={'placeholder': 'Notify on what % drop after alert price'}))
    intraday_alert = BooleanField(required=False)

stock_price_alert/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from phonenumber_field.formfields import PhoneNumberField

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

stock_price_alert/alerts/views.py
import json
import logging
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status
from .models import Alert
from .serializers import AlertSerializer

logging.basicConfig(filename='alerts.log',
                    filemode='a',
                    format='%(asctime)s,%(msecs)d %(name)s %(levelname)s %(message)s',
                    datefmt='%H:%M:%S',
                    level=logging.INFO)
log = logging.getLogger(__name__)


@login_required()
def view_alerts(request):
    alerts = Alert.objects.filter(user=request.user).order_by('scrip_symbol')
    # helper.template = 'bootstrap/table_inline_formset.html'

    return render(request, 'alerts/set_alerts.html', {'alerts': alerts})


@login_required
@api_view(['POST'])
@permission_classes((IsAuthenticated,))
def add_alerts(request):
    data = list(request.data)
    error_message = None
    for datum in data:
        if datum.get('uuid', None):
            alert_obj = Alert.objects.get(uuid=datum['uuid'])
            alert_serializer = AlertSerializer(alert_obj, data=datum)
        else:
            alert_serializer = AlertSerializer(data=datum)

        if alert_serializer.is_valid():
            alert_serializer.save()
        else:
            log.exception(alert_serializer.errors)
            error_message = alert_serializer.error_messages
            log.exception(alert_serializer.error_messages)
    if error_message:
        return Response({'message': error_message}, status=status.HTTP_400_BAD_REQUEST)
    else:
        return Response({'message': 'Success'}, status=status.HTTP_200_OK)


@login_required
@api_view(['POST'])
@permission_classes((IsAuthenticated,))
def remove_alert(request):
    data = request.data
    error_message = None
    try:
        alert = Alert.objects.get(uuid=data['uuid'])
        alert.delete()
    except Alert.DoesNotExist:
        error_message = 'Alert object does not exist.'
    if error_message:
        return Response({'message': error_message}, status=status.HTTP_400_BAD_REQUEST)
    else:
        return Response({'message': 'Success'}, status=status.HTTP_200_OK)

stock_price_alert/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name", "phone_number"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

stock_price_alert/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

stock_price_alert/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Stock Price Alert{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap 4.1.1 CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->
      <!-- Font Awesome -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Bootstrap core CSS -->
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/css/mdb.min.css" rel="stylesheet">

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light my-bg">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' as home_url %}">Stock Price Alert</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto" data-id="">
            <li class="nav-item {% if request.get_full_path == home_url %} active {% endif %}">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.get_full_path == 'about' %} active {% endif %}">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item ">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>

            {% else %}
              <li class="nav-item {% if request.get_full_path == 'account_signup' %} active {% endif %}">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item {% if request.get_full_path == 'account_login' %} active {% endif %}">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>

            {% endif %}
          {% if request.user.is_authenticated %}
              <li class="nav-item">

                  <a id="alert-link" class="nav-link" href="{% url 'alerts:view_alerts' %}">{% trans "Alerts" %}</a>

              </li>
              <li class="nav-item {% if request.get_full_path == 'account_logout' %} active {% endif %}">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
          {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <br>
        <p>Welcome to Stock Price Alert service.</p>
        <p>Here you can set alerts for NSE or NASDAQ stocks according to various parameters.</p>
        {% if request.user.is_authenticated %}
          <p>Please click <a href="{% url 'alerts:view_alerts' %}">here</a> to view alerts.</p>
        {% else %}
          <p>Please <a href="{% url 'account_signup' %}">sign-up</a> or <a href="{% url 'account_login' %}">login</a> to continue.</p>
        {% endif %}
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Required by Bootstrap v4.1.1 -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

        <!-- JQuery -->

<!-- Bootstrap tooltips -->
<!-- Bootstrap core JavaScript -->
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/js/mdb.min.js"></script>



      <!-- place project specific Javascript in this file -->


      <script src="{% static 'js/secure_ajax_handler.js' %}"></script>
      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>

stock_price_alert/templates/mail_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Price Alert</title>
</head>
<body>
<div>
  <span style="text-align: center">{{ scrip_symbol }}</span>
  {% if percentage %}
      <span style="text-align: center">Your price of {{ price }} with a tolerance of {{ percentage }}%  has been hit on {{ date }}.</span>
  {% else %}
    <span style="text-align: center">Your price of {{ price }} has been hit on {{ date }}.</span>
  {% endif %}
  <span>Some more information for the day is given below.</span>
  </div>


<table align="center" class="alert-table">

  <tr>
    <th>Open Price</th>
    <th>Close Price</th>
    <th>High</th>
    <th>Low</th>
    <th>Traded Volume</th>
    <th>Total Buy</th>
    <th>Total Sell</th>
    <th>52 Week Low</th>
    <th>52 Week High</th>
  </tr>
  <tr>
    <td>{{ open }}</td>
    <td>{{ close }}</td>
    <td>{{ high }}</td>
    <td>{{ low }}</td>
    <td>{{ traded_volume }}</td>
    <td>{{ total_buy }}</td>
    <td>{{ total_sell }}</td>
    <td>{{ week_low }}</td>
    <td>{{ week_high }}</td>
  </tr>
</table>

From : {{ site }}
</body>
</html>